version: '3'
services:
  
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres179
      - POSTGRES_PASSWORD=MZth2BRdEpAI
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - dragonflydata:/data
      
  kalaha-1:
    image: kalaha:latest
    ports:
      - "8080:8080"
    depends_on:
      - dragonfly
      - db
    environment:
        DB_HOST: db
        REDIS_HOST: dragonfly
    links:
      - db
      - dragonfly

  kalaha-2:
    image: kalaha:latest
    ports:
      - "8081:8080"
    depends_on:
      - dragonfly
      - db
    environment:
        DB_HOST: db
        REDIS_HOST: dragonfly
    links:
      - db
      - dragonfly
  
volumes:
  dragonflydata:
  db:
    driver: local